version: '3'
services:
  kafka1:
    image: apache/kafka:latest
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9095,3@kafka3:9097
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
  kafka2:
    image: apache/kafka:latest
    container_name: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@kafka2:9095,1@kafka1:9093,3@kafka3:9097
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
  kafka3:
    image: apache/kafka:latest
    container_name: kafka3
    ports:
      - "9096:9096"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096,CONTROLLER://0.0.0.0:9097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9096
      KAFKA_CONTROLLER_QUORUM_VOTERS: 2@kafka2:9095,1@kafka1:9093,3@kafka3:9097
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw

  
  ## How KRaft Cluster Discovery Works
  
  ### 1. Controller Quorum Formation

#  Kafka1 ──┐
#  Kafka2 ──┼──► All look at KAFKA_CONTROLLER_QUORUM_VOTERS
#  Kafka3 ──┘     to find each other
#---------------------------------------------------------
#  kafka-setup:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - kafka1
#    command: >
#      bash -c "
#        echo 'Waiting for Kafka to be ready...'
#        sleep 10
#        echo 'success'
#      "
#---------------------------------------------------------
#        kafka-topics --create --if-not-exists \
#          --topic orders \
#          --partitions 6 \
#          --replication-factor 3 \
#          --bootstrap-server kafka1:29092
#
#        kafka-topics --create --if-not-exists \
#          --topic payments \
#          --partitions 6 \
#          --replication-factor 3 \
#          --bootstrap-server kafka1:29092
#
#        kafka-topics --create --if-not-exists \
#          --topic notifications \
#          --partitions 3 \
#          --replication-factor 2 \
#          --bootstrap-server kafka1:29092
#
#        echo 'Topics created successfully!'
#      "